### ISSUE TITLE
copyByte 是否存在问题

### ISSUE THREAD

**Issue by mini-bix** [Allenxuxu/ringbuffer#3]
func copyByte(f, e []byte) []byte {
	buf := make([]byte, len(f)+len(e))
	_ = copy(buf, f)
        //这个地方是不应该这样写
	_ = copy(buf[len(f):], e) 
	return buf
}

**Comment by Allenxuxu** [comment]
> func copyByte(f, e []byte) []byte {
> buf := make([]byte, len(f)+len(e))
> _ = copy(buf, f)
> //这个地方是不应该这样写
> _ = copy(buf[len(f):], e)
> return buf
> }

这确实是一个低级的 bug 😅，非常感谢指出！

**Comment by Allenxuxu** [comment]
已经修复了这个 bug 😄，非常感谢！
