### ISSUE TITLE
Bytes() function 返回数据有问题

### ISSUE THREAD

**Issue by Enan01** [Allenxuxu/ringbuffer#6]
问题代码如下：

```go
	if r.w == r.r {
		if !r.isEmpty {
			buf := make([]byte, r.size)
			copy(buf, r.buf)
			return buf
		}
		return
	}
```

如果 `r.w == r.r && r.w != 0`, 不能直接 `copy(buf, r.buf)`

提交了一个 pr：https://github.com/Allenxuxu/ringbuffer/pull/5

@Allenxuxu

**Comment by Allenxuxu** [comment]
非常感谢发现并修复这个 bug  🥳
